:concurrency: 3
:timeout: 60
:verbose: true
:queues:
  - critical
  - default
  - mailers
  - active_storage_analysis
  - active_storage_purge
tasks: &tasks
  YourBackgroundJob:
    # every minute
    cron: "*/1 * * * *"
    queue: default
    description: "Write the utility of the job"
:scheduler:
  :schedule:
    <<: *tasks